import random
import json
from datetime import datetime


class EdgeDevice:
    """
    Edge Device Class
    Represents Edge layer devices (sensors/cameras) in Fog Computing architecture.
    Responsible for:
    - Simulating IoT sensors and cameras
    - Generating raw traffic data
    - Sending data to Fog layer for processing
    """
    
    def __init__(self, device_id, location):
        """
        Initialize an Edge Device
        
        Args:
            device_id (str): Unique identifier for the device
            location (str): Physical location of the device
        """
        self.device_id = device_id
        self.location = location
        self.data_sent_count = 0
        
    def generate_traffic_data(self):
        """
        Simulate traffic sensor generating vehicle count and related data
        This represents raw data collection at the edge
        
        Returns:
            dict: Simulated traffic data in JSON format
        """
        vehicle_count = random.randint(5, 120)
        
        speed_avg = random.randint(20, 80)
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        data = {
            "device_id": self.device_id,
            "location": self.location,
            "vehicle_count": vehicle_count,
            "average_speed_kmh": speed_avg,
            "timestamp": timestamp,
            "data_type": "traffic_sensor",
            "sensor_status": "active"
        }
        
        self.data_sent_count += 1
        
        print(f"\n{'~'*60}")
        print(f"[EDGE LAYER] Data Generated by {self.device_id}")
        print(f"{'~'*60}")
        print(f"Location: {self.location}")
        print(f"Timestamp: {timestamp}")
        print(f"Vehicle Count: {vehicle_count}")
        print(f"Average Speed: {speed_avg} km/h")
        print(f"Total Data Sent: {self.data_sent_count}")
        print(f"[EDGE] → Sending to FOG LAYER...")
        print(f"{'~'*60}\n")
        
        return data
    
    def get_device_info(self):
        """
        Get information about this edge device
        
        Returns:
            dict: Device information
        """
        return {
            "device_id": self.device_id,
            "location": self.location,
            "total_data_sent": self.data_sent_count,
            "status": "active"
        }


def create_sample_devices():
    """
    Create sample edge devices for demonstration
    
    Returns:
        list: List of EdgeDevice instances
    """
    devices = [
        EdgeDevice("EDGE_CAM_001", "MG Road Junction"),
        EdgeDevice("EDGE_CAM_002", "City Center Square"),
        EdgeDevice("EDGE_CAM_003", "Highway Toll Plaza"),
        EdgeDevice("EDGE_SENSOR_004", "Railway Station Road"),
        EdgeDevice("EDGE_SENSOR_005", "Airport Avenue")
    ]
    return devices
